name: GitHub Actions Demo
run-name: ${{ github.actor }} this my first devops 🚀
on: 
    push:
      branches: [main]
    pull_request: 
      branches: [main]  
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.19.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modiles
        run: yarn install
      - name: build project
        run: yarn build
      - name: linter
        run: yarn lint
 